
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by CSGenerator.
// </auto-generated>
//------------------------------------------------------------------------------
using SharpKit.JavaScript;

[assembly: JsExport(Minify = false, DefaultFilename = "Assets/StreamingAssets/JavaScript/SharpKitGeneratedFiles.javascript")]

#region JsType
[assembly: JsType(TargetTypeName = "ComponentExtension", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "jsimp.Coroutine", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "jsimp.Misc", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "jsimp.Reflection", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "DelegateTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "DictionaryTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "EncodingTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LoginManager", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TestLogin", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "EventTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ListTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "PerformanceTest1", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SampleViewer", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SampleViewer+stScene", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "V3Test", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeA", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeB", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeC", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "CallJSTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ComponentTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MentosKXT", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TEnemy", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TEnemyBase", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TestCoroutine", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JSImpTest1", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JSImpTest1+Person", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "XmlParser", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MiscTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AnimationCurveTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Car", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeSimple", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeStruct", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeStruct+AppleInfo", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Wheel", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Wheel+Pos", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "StreamTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MindActUpMide`1", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "XmlTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ShopItemData", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LimitDayNum", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LimitVIPLevel", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LimitBuyNumPrices", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LimitVipDayNum", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LimeTimeNum", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "IShopLime", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ItemType", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ItemCell", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ColorSign", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "enumMoneyType", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Lavie.XmlUtils", Mode = JsMode.Clr)]

#endregion