using UnityEngine;
public class CSGenerateRegister
{
    public static void RegisterAll()
    {
        if (JSMgr.allCallbackInfo.Count != 0)
        {
            Debug.LogError("Has already register CS binding");
        }
        PerTestGenerated.__Register();
        PerTest_RefObjectGenerated.__Register();
        System_Collections_IEnumeratorGenerated.__Register();
        System_Collections_ICollectionGenerated.__Register();
        System_IDisposableGenerated.__Register();
        System_IConvertibleGenerated.__Register();
        System_Diagnostics_StopwatchGenerated.__Register();
        System_Text_StringBuilderGenerated.__Register();
        System_TimeSpanGenerated.__Register();
        System_DateTimeGenerated.__Register();
        System_Xml_XmlNodeGenerated.__Register();
        System_Runtime_Serialization_ISerializableGenerated.__Register();
        System_Runtime_InteropServices__ExceptionGenerated.__Register();
        System_Runtime_Serialization_ISurrogateSelectorGenerated.__Register();
        System_Xml_XPath_IXPathNavigableGenerated.__Register();
        System_ICloneableGenerated.__Register();
        System_Collections_IEnumerableGenerated.__Register();
        System_Xml_XmlDocumentGenerated.__Register();
        System_Xml_XmlNodeListGenerated.__Register();
        System_Xml_XmlElementGenerated.__Register();
        System_Xml_XmlLinkedNodeGenerated.__Register();
        System_Xml_XmlAttributeCollectionGenerated.__Register();
        System_Xml_XmlNamedNodeMapGenerated.__Register();
        System_Xml_XmlAttributeGenerated.__Register();
        UnityEngine_ISerializationCallbackReceiverGenerated.__Register();
        UnityEngine_UnityExceptionGenerated.__Register();
        UnityEngine_ScriptableObjectGenerated.__Register();
        UnityEngine_DebugGenerated.__Register();
        UnityEngine_InputGenerated.__Register();
        UnityEngine_GameObjectGenerated.__Register();
        UnityEngine_TransformGenerated.__Register();
        UnityEngine_Vector2Generated.__Register();
        UnityEngine_Vector3Generated.__Register();
        UnityEngine_Vector4Generated.__Register();
        UnityEngine_QuaternionGenerated.__Register();
        UnityEngine_MonoBehaviourGenerated.__Register();
        UnityEngine_BehaviourGenerated.__Register();
        UnityEngine_ComponentGenerated.__Register();
        UnityEngine_ObjectGenerated.__Register();
        UnityEngine_YieldInstructionGenerated.__Register();
        UnityEngine_WaitForSecondsGenerated.__Register();
        UnityEngine_WWWGenerated.__Register();
        UnityEngine_ApplicationGenerated.__Register();
        UnityEngine_TimeGenerated.__Register();
        UnityEngine_ResourcesGenerated.__Register();
        UnityEngine_TextAssetGenerated.__Register();
        UnityEngine_RandomGenerated.__Register();
        UnityEngine_LayerMaskGenerated.__Register();
        UnityEngine_AudioClipGenerated.__Register();
        UnityEngine_AudioSourceGenerated.__Register();
        UnityEngine_ParticleSystemGenerated.__Register();
        UnityEngine_RendererGenerated.__Register();
        UnityEngine_ParticleSystemRendererGenerated.__Register();
        UnityEngine_AnimatorGenerated.__Register();
        UnityEngine_CameraGenerated.__Register();
        UnityEngine_MathfGenerated.__Register();
        UnityEngine_MaterialGenerated.__Register();
        UnityEngine_ColorGenerated.__Register();
        UnityEngine_Color32Generated.__Register();
        UnityEngine_LightGenerated.__Register();
        UnityEngine_NavMeshAgentGenerated.__Register();
        UnityEngine_NavMeshPathGenerated.__Register();
        UnityEngine_BoundsGenerated.__Register();
        UnityEngine_RectGenerated.__Register();
        UnityEngine_RectOffsetGenerated.__Register();
        UnityEngine_PhysicsGenerated.__Register();
        UnityEngine_RaycastHitGenerated.__Register();
        UnityEngine_RigidbodyGenerated.__Register();
        UnityEngine_ColliderGenerated.__Register();
        UnityEngine_SphereColliderGenerated.__Register();
        UnityEngine_BoxColliderGenerated.__Register();
        UnityEngine_CapsuleColliderGenerated.__Register();
        UnityEngine_MeshColliderGenerated.__Register();
        UnityEngine_LineRendererGenerated.__Register();
        UnityEngine_MeshRendererGenerated.__Register();
        UnityEngine_ScreenGenerated.__Register();
        UnityEngine_AnimatorStateInfoGenerated.__Register();

    }
}
