
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by CSGenerator.
// </auto-generated>
//------------------------------------------------------------------------------
using SharpKit.JavaScript;

[assembly: JsExport(Minify = false, DefaultFilename = "Assets/StreamingAssets/JavaScript/SharpKitGeneratedFiles.javascript")]

#region JsType

#endregion